spring:
  application:
    name: mediaService

  data:
    mongodb:
      database: media

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB # allow only images for now
      max-request-size: 20MB

file:
  upload-dir: C:\Users\Yqssine\OneDrive\Documents\IT_Career\JEE\Projet\resources
  path:
    prefix: /images

server:
  port: 8000

# security:
#   basic:
#     enable: false

#   jwt:
#     uri: /auth/**
#     header: Authorization
#     prefix: Bearer
#     expiration: 86400
#     secret: JwtSecretKey

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka